// src/views/tray/SocialLinks.vue
<script setup lang="ts">
import { computed, ref } from 'vue'
import { onLongPress } from '@vueuse/core'
import { NotificationApi } from '@widget-js/core'
import { useI18n } from 'vue-i18n'
import { useDebugConfig } from '@/composition/useAppConfig'

const props = defineProps({
  iconSize: {
    type: Number,
    default: 20,
  },
})

const debugMode = useDebugConfig()
const github = ref()
const { t } = useI18n()
onLongPress(
  github,
  () => {
    NotificationApi.info(t('notification.enableDevMode'))
    debugMode.value = true
  },
  { delay: 3000 },
)
const iconSizePx = computed(() => `${props.iconSize}px`)
</script>

<template>
  <div class="social">
    <a target="_blank" href="https://widgetjs.cn/">
      <img src="../../assets/images/logo.png" alt="Widget"></a>
    <a target="_blank" href="https://v.douyin.com/YhuNAb8/">
      <img src="../../assets/images/douyin.png" alt="TikTok"></a>

    <a target="_blank" href="https://jq.qq.com/?_wv=1027&k=TgO2mUQe">
      <img src="../../assets/images/qq.png" alt="QQ"></a>

    <a target="_blank" href="https://space.bilibili.com/207395767">
      <img src="../../assets/images/bilibili_logo_red.png" alt="Bilibili"></a>
    <a ref="github" target="_blank" href="https://github.com/widget-js/widgets">
      <img src="../../assets/images/github-mark.png" alt="GitHub"></a>
  </div>
</template>

<style scoped lang="scss">
@import '@/assets/scss/theme.scss';

.social {
  display: flex;
  justify-content: flex-start;
  align-items: center;
  gap: 0.8rem;

  a {
    text-decoration: none;
    color: $color-primary;
    line-height: 0;
    img {
      width: v-bind(iconSizePx);
    }
  }
}
</style>

// src/components/tray/social-links.tsx
import { AppApi, NotificationApi } from '@widget-js/core'
import { useCallback, useRef } from 'react'
import { useTranslation } from 'react-i18next'
import bilibili from '@/assets/images/bilibili_logo_red.png'
import douyin from '@/assets/images/douyin.png'
import githubMark from '@/assets/images/github-mark.png'
import logo from '@/assets/images/logo.png'
import qq from '@/assets/images/qq.png'

interface SocialLinksProps {
  iconSize?: number
}

function useLongPress(callback: () => void, delay: number = 3000) {
  const timeoutRef = useRef<number | null>(null)

  const start = useCallback(() => {
    timeoutRef.current = window.setTimeout(() => {
      callback()
    }, delay)
  }, [callback, delay])

  const clear = useCallback(() => {
    if (timeoutRef.current) {
      clearTimeout(timeoutRef.current)
      timeoutRef.current = null
    }
  }, [])

  return {
    onMouseDown: start,
    onMouseUp: clear,
    onMouseLeave: clear,
    onTouchStart: start,
    onTouchEnd: clear,
  }
}

export function SocialLinks({ iconSize = 20 }: SocialLinksProps) {
  const { t } = useTranslation()

  const handleEnableDevMode = useCallback(async () => {
    NotificationApi.info(t('notification.enableDevMode'))
    await AppApi.setConfig('debug', true)
  }, [t])

  const longPressProps = useLongPress(handleEnableDevMode, 3000)

  const links = [
    {
      name: 'Widget',
      url: 'https://widgetjs.cn/',
      icon: logo,
    },
    {
      name: 'TikTok',
      url: 'https://v.douyin.com/YhuNAb8/',
      icon: douyin,
    },
    {
      name: 'QQ',
      url: 'https://jq.qq.com/?_wv=1027&k=TgO2mUQe',
      icon: qq,
    },
    {
      name: 'Bilibili',
      url: 'https://space.bilibili.com/207395767',
      icon: bilibili,
    },
    {
      name: 'GitHub',
      url: 'https://github.com/widget-js/widgets',
      icon: githubMark,
      ...longPressProps, // Apply long press to GitHub only
    },
  ]

  return (
    <div className="flex items-center justify-start gap-[0.8rem]">
      {links.map(link => (
        <a
          key={link.name}
          href={link.url}
          target="_blank"
          rel="noopener noreferrer"
          className="text-primary no-underline leading-none hover:opacity-80 transition-opacity"
          {...(link.name === 'GitHub' ? longPressProps : {})}
        >
          <img
            src={link.icon}
            alt={link.name}
            style={{ width: `${iconSize}px`, height: `${iconSize}px` }}
            className="object-contain"
          />
        </a>
      ))}
    </div>
  )
}
