// src/views/manager/WidgetPackageItem.vue
<script setup lang="ts">
import type { PropType } from 'vue'
import type { WidgetPackage } from '@widget-js/core'
import { useI18n } from 'vue-i18n'

defineProps({
  widgetPackage: {
    type: Object as PropType<WidgetPackage>,
    required: true,
  },
})

const emits = defineEmits(['uninstall'])

const { t } = useI18n()
</script>

<template>
  <ElCard shadow="hover" body-style="padding:12px">
    <div class="flex">
      <div class="flex flex-col gap-2">
        <div class="flex flex-col text-start">
          <div v-if="widgetPackage">
            <b>{{ t('settings.widgetPackage.title') }}</b>{{ widgetPackage.getTitle() }}
          </div>
          <div class="flex gap-6">
            <span><b>{{ t('settings.widgetPackage.name') }}</b>{{ widgetPackage.name }}</span>
          </div>
          <div class="flex">
            <div><b>{{ t('settings.widgetPackage.installPath') }}</b></div><el-text truncated style="max-width: 600px">
              {{ widgetPackage.url }}
            </el-text>
          </div>
        </div>
      </div>
      <div class="ml-auto flex items-center">
        <el-popconfirm
          :cancel-button-text="t('settings.widgetPackage.cancel')"
          width="200"
          :confirm-button-text="t('settings.widgetPackage.confirm')"
          :title="t('settings.widgetPackage.uninstallConfirm')" @confirm="emits('uninstall', widgetPackage)"
        >
          <template #reference>
            <el-button type="danger" size="small">
              {{ t('settings.widgetPackage.uninstall') }}
            </el-button>
          </template>
        </el-popconfirm>
      </div>
    </div>
  </ElCard>
</template>

<style scoped lang="scss">

</style>

// src/pages/packages/components/widget-package-item.tsx
import type { LanguageCode, WidgetPackage } from '@widget-js/core'
import { useTranslation } from 'react-i18next'
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from '@/components/ui/alert-dialog'
import { Button } from '@/components/ui/button'
import { Card } from '@/components/ui/card'
import { useAppLanguage } from '@/hooks/use-app-language'

interface WidgetPackageItemProps {
  widgetPackage: WidgetPackage
  onUninstall: (pkg: WidgetPackage) => void
}

export function WidgetPackageItem({ widgetPackage, onUninstall }: WidgetPackageItemProps) {
  const { t } = useTranslation()
  const [languageCode] = useAppLanguage()

  const getTitle = (): string => {
    if (typeof widgetPackage.getTitle === 'function') {
      return widgetPackage.getTitle(languageCode as LanguageCode) || widgetPackage.name
    }
    return widgetPackage.name
  }

  return (
    <Card className="p-3 shadow-sm hover:shadow-md transition-shadow">
      <div className="flex items-center gap-4">
        <div className="flex flex-col gap-1 flex-1 min-w-0 text-left">
          <div className="flex items-center gap-2 text-sm">
            <span className="font-bold shrink-0">{t('settings.widgetPackage.title')}</span>
            <span className="truncate">{getTitle()}</span>
          </div>
          <div className="flex items-center gap-2 text-sm">
            <span className="font-bold shrink-0">{t('settings.widgetPackage.name')}</span>
            <span className="truncate text-muted-foreground">{widgetPackage.name}</span>
          </div>
          <div className="flex items-center gap-2 text-sm">
            <span className="font-bold shrink-0">{t('settings.widgetPackage.installPath')}</span>
            <span className="truncate text-muted-foreground max-w-[400px]" title={widgetPackage.url}>
              {widgetPackage.url}
            </span>
          </div>
        </div>

        <div className="ml-auto flex items-center">
          <AlertDialog>
            <AlertDialogTrigger asChild>
              <Button variant="destructive" size="sm">
                {t('settings.widgetPackage.uninstall')}
              </Button>
            </AlertDialogTrigger>
            <AlertDialogContent>
              <AlertDialogHeader>
                <AlertDialogTitle>{t('settings.widgetPackage.uninstallConfirm')}</AlertDialogTitle>
                <AlertDialogDescription>
                  {t('settings.widgetPackage.uninstallDesc', { name: getTitle() })}
                </AlertDialogDescription>
              </AlertDialogHeader>
              <AlertDialogFooter>
                <AlertDialogCancel>{t('settings.widgetPackage.cancel')}</AlertDialogCancel>
                <AlertDialogAction onClick={() => onUninstall(widgetPackage)}>
                  {t('settings.widgetPackage.confirm')}
                </AlertDialogAction>
              </AlertDialogFooter>
            </AlertDialogContent>
          </AlertDialog>
        </div>
      </div>
    </Card>
  )
}
