// src/views/add/SearchItem.vue
<script lang="ts">
import {
  AppApi,
  BrowserWindowApi,
  DeployMode,
  DeployedWidgetApi,
  NotificationApi,
  WidgetApi,
  WidgetPackageUtils,
  WidgetParams,
} from '@widget-js/core'
import { useBroadcastChannel } from '@vueuse/core'
import { ref } from 'vue'
import { WebWidget } from '@widget-js/web-api'
import { ArrowCircleUp } from '@icon-park/vue-next'
import { useI18n } from 'vue-i18n'
import semver from 'semver'
import WidgetContainer from '@/views/add/WidgetContainer.vue'
import { useDebugConfig } from '@/composition/useAppConfig'
import { useWidgetPackage } from '@/composition/useWidgetPackage'
import WidgetUtil from '@/utils/WidgetUtil'

export default {
  name: 'SearchItem',
  components: { WidgetContainer, ArrowCircleUp },
  props: {
    widget: {
      type: WebWidget,
      required: true,
    },
  },
  setup(props) {
    const i18n = useI18n()
    const isWidgetHosted = ref(false)
    const adding = ref(false)
    const { post } = useBroadcastChannel({ name: 'CHANNEL_MAIN' })
    const updateWidgetAdd = async () => {
      if (props.widget.isSupportBackground()) {
        const widgets = await DeployedWidgetApi.getDeployedWidgets(props.widget.name)
        if (widgets) {
          isWidgetHosted.value = widgets.length > 0
        }
        else {
          isWidgetHosted.value = false
        }
      }
    }
    const isDev = useDebugConfig()
    updateWidgetAdd()
    const remotePackage = props.widget.package
    const { upgradable, upgrading, checkUpgrade, upgradePackage } = useWidgetPackage(
      props.widget.packageName!,
      remotePackage?.version ?? '0.0.0',
      remotePackage?.remote,
    )
    return {
      upgrading,
      upgradable,
      checkUpgrade,
      upgradePackage,
      isDev,
      post,
      i18n,
      isWidgetHosted,
      updateWidgetAdd,
      adding,
    }
  },
  computed: {
    WidgetUtil() {
      return WidgetUtil
    },
    DeployMode() {
      return DeployMode
    },
  },
  mounted() {
    this.checkUpgrade()
  },
  methods: {
    BrowserWindowApi() {
      return BrowserWindowApi
    },
    async removeWidget() {
      await DeployedWidgetApi.removeDeployedWidgetByName(this.widget.name)
      await this.updateWidgetAdd()
    },
    async upgrade() {
      this.upgradePackage()
    },
    openDevTools() {
      DeployedWidgetApi.openDevTools(this.widget.name)
    },
    async addWidget(mode: DeployMode) {
      try {
        this.adding = true
        let versionPass = true
        const appVersion = await AppApi.getVersion('app')
        // If appVersion is undefined, it means the app is running at browser
        if (this.widget.requiredAppVersion && appVersion) {
          if (semver.gte(appVersion, this.widget.requiredAppVersion)) {
            versionPass = true
          }
          else {
            versionPass = false
            NotificationApi.error(
              this.i18n.t('update.upgradeToNew'),
            )
          }
        }
        if (versionPass) {
          const url = this.widget.package?.remote
            ? WidgetPackageUtils.getRemotePackageJsonUrl(this.widget.package?.remote)
            : undefined
          await DeployedWidgetApi.addWidget({
            widgetName: this.widget.name,
            deployMode: mode,
            packageJsonUrl: url,
          })
        }
      }
      finally {
        this.adding = false
      }
    },
    async addBackgroundWidget() {
      await this.addWidget(DeployMode.BACKGROUND)
      await this.updateWidgetAdd()
    },
    async openBackgroundWidgetSettings() {
      const widgetParams = new WidgetParams()
      widgetParams.id = this.widget.name
      widgetParams.name = this.widget.name
      WidgetApi.openConfigPageByName(this.widget.name)
    },
    async onClickAddNormal() {
      await this.addWidget(DeployMode.NORMAL)
    },
  },
}
</script>

<template>
  <div v-loading="adding" class="search-item">
    <div class="flex w-full">
      <div class="flex flex-col items-start">
        <span class="title">{{ widget.getTitle(i18n.locale.value) }}</span>
        <span class="desc">{{ widget.getDescription(i18n.locale.value) }} </span>
      </div>
      <div v-if="widget.socialLinks" class="ml-auto flex gap-2">
        <img v-for="social in widget.socialLinks.slice(0, 3)" :key="social.name" class="cursor-pointer h-6" :src="WidgetUtil.getSocialLinkIcon(social.name)" :alt="social.name" @click="BrowserWindowApi().openUrl(social.link, { external: true })">
      </div>
    </div>
    <WidgetContainer class="widget" :widget="widget" />
    <div class="flex gap-4">
      <div class="flex">
        <template v-if="widget.isSupportBackground()">
          <el-button v-show="widget.isConfigurable()" type="primary" round @click="openBackgroundWidgetSettings">
            {{ i18n.t("settings.title") }}
          </el-button>
          <el-button v-if="!isWidgetHosted" type="primary" round @click="addBackgroundWidget">
            {{ i18n.t("search.enable") }}
          </el-button>
          <el-button v-if="isWidgetHosted" type="danger" round @click="removeWidget">
            {{ i18n.t("search.disable") }}
          </el-button>
          <el-button v-if="isWidgetHosted && isDev" type="warning" round @click="openDevTools">
            DevTools
          </el-button>
        </template>
        <template v-else>
          <el-button v-if="widget.isSupportNormal()" type="primary" round @click="onClickAddNormal">
            {{ i18n.t("search.desktop") }}
          </el-button>
          <el-button v-if="widget.isSupportOverlap()" type="primary" round @click="addWidget(DeployMode.OVERLAP)">
            {{ i18n.t("search.overlap") }}
          </el-button>
          <el-button v-if="widget.isSupportTray()" type="primary" round @click="addWidget(DeployMode.TRAY)">
            {{ i18n.t("search.tray") }}
          </el-button>
        </template>
      </div>
      <el-button v-if="upgradable" v-loading="upgrading" type="warning" round @click="upgrade">
        <template #icon>
          <ArrowCircleUp />
        </template>
        {{ i18n.t("search.upgrade") }}
      </el-button>
    </div>
  </div>
</template>

<style scoped lang="scss">
@use "sass:map";
@import "element-plus/theme-chalk/src/common/var.scss";

.search-item {
  margin-bottom: 20px;
  display: flex;
  background-color: white;
  border-radius: 16px;
  flex-direction: column;
  align-items: center;
  padding: 16px;

  .title {
    font-size: 16px;
    font-weight: bold;
    color: map.get($text-color, "primary");
    margin-bottom: 8px;
  }

  .desc {
    color: map.get($text-color, "secondary");
  }

  .widget {
    margin: 16px;
  }

  .buttons {
    justify-content: center;
    align-items: center;
    align-content: center;
    display: flex;

    .el-button {
      width: 70px;
    }
  }
}
</style>

// src/pages/add/components/search-item.tsx
import type { WebWidget } from '@widget-js/web-api'
import {
  AppApi,
  BrowserWindowApi,
  DeployedWidgetApi,
  DeployMode,
  NotificationApi,
  WidgetApi,
  WidgetPackageUtils,
} from '@widget-js/core'
import { ArrowUpCircle, Loader2 } from 'lucide-react'
import { useCallback, useEffect, useState } from 'react'
import { useTranslation } from 'react-i18next'
import semver from 'semver'
import { Button } from '@/components/ui/button'
import { Card } from '@/components/ui/card'
import { useDebugConfig } from '@/hooks/use-debug-config'
import { useWidgetPackage } from '@/hooks/use-widget-package'
import WidgetUtil from '@/utils/widget-util'
import WidgetContainer from './widget-container'

interface SearchItemProps {
  widget: WebWidget
}

export function SearchItem({ widget }: SearchItemProps) {
  const { t, i18n } = useTranslation()
  const [isDev] = useDebugConfig()
  const [isWidgetHosted, setIsWidgetHosted] = useState(false)
  const [adding, setAdding] = useState(false)

  const updateWidgetAdd = useCallback(async () => {
    if (widget.isSupportBackground()) {
      const widgets = await DeployedWidgetApi.getDeployedWidgets(widget.name)
      if (widgets) {
        setIsWidgetHosted(widgets.length > 0)
      }
      else {
        setIsWidgetHosted(false)
      }
    }
  }, [widget])

  useEffect(() => {
    updateWidgetAdd()
  }, [updateWidgetAdd])

  const remotePackage = widget.package
  const { upgradable, upgrading, checkUpgrade, upgradePackage } = useWidgetPackage(
    widget.packageName!,
    remotePackage?.version ?? '0.0.0',
    remotePackage?.remote,
  )

  useEffect(() => {
    checkUpgrade()
  }, [checkUpgrade])

  const removeWidget = async () => {
    await DeployedWidgetApi.removeDeployedWidgetByName(widget.name)
    await updateWidgetAdd()
  }

  const openDevTools = () => {
    DeployedWidgetApi.openDevTools(widget.name)
  }

  const addWidget = async (mode: DeployMode) => {
    try {
      setAdding(true)
      let versionPass = true
      const appVersion = await AppApi.getVersion('app')

      if (widget.requiredAppVersion && appVersion) {
        if (semver.gte(appVersion, widget.requiredAppVersion)) {
          versionPass = true
        }
        else {
          versionPass = false
          NotificationApi.error(t('update.upgradeToNew', 'Please upgrade app'))
        }
      }

      if (versionPass) {
        const url = widget.package?.remote
          ? WidgetPackageUtils.getRemotePackageJsonUrl(widget.package?.remote)
          : undefined

        await DeployedWidgetApi.addWidget({
          widgetName: widget.name,
          deployMode: mode,
          packageJsonUrl: url,
        })
      }
    }
    finally {
      setAdding(false)
    }
  }

  const addBackgroundWidget = async () => {
    await addWidget(DeployMode.BACKGROUND)
    await updateWidgetAdd()
  }

  const openBackgroundWidgetSettings = async () => {
    WidgetApi.openConfigPageByName(widget.name)
  }

  const onClickAddNormal = async () => {
    await addWidget(DeployMode.NORMAL)
  }

  // Helper to get localized text
  const getLocalizedText = (obj: any) => {
    if (typeof obj === 'string') { return obj }
    if (!obj) { return '' }
    return obj[i18n.language] || obj.en || Object.values(obj)[0] || ''
  }

  const title = getLocalizedText(widget.title)
  const description = getLocalizedText(widget.description)

  return (
    <Card className="flex flex-col p-4 bg-white rounded-xl mb-5 items-center relative">
      {adding && (
        <div className="absolute inset-0 bg-background/50 flex items-center justify-center z-10 rounded-xl backdrop-blur-[1px]">
          <Loader2 className="animate-spin h-8 w-8 text-primary" />
        </div>
      )}

      <div className="flex w-full">
        <div className="flex flex-col items-start">
          <span className="text-base font-bold text-primary mb-2">{title}</span>
          <span className="text-muted-foreground text-sm">{description}</span>
        </div>
        {widget.socialLinks && (
          <div className="ml-auto flex gap-2">
            {widget.socialLinks.slice(0, 3).map((social: any) => (
              <img
                key={social.name}
                className="cursor-pointer h-6 w-6 object-contain hover:opacity-80 transition-opacity"
                src={WidgetUtil.getSocialLinkIcon(social.name)}
                alt={social.name}
                onClick={() => BrowserWindowApi.openUrl(social.link, { external: true })}
              />
            ))}
          </div>
        )}
      </div>

      <WidgetContainer className="m-4 w-full border-none shadow-none" widget={widget} />

      <div className="flex gap-4 flex-wrap justify-center">
        <div className="flex gap-2 flex-wrap justify-center">
          {widget.isSupportBackground()
            ? (
                <>
                  {widget.isConfigurable() && (
                    <Button onClick={openBackgroundWidgetSettings} className="rounded-full">
                      {t('settings.title', 'Settings')}
                    </Button>
                  )}
                  {!isWidgetHosted
                    ? (
                        <Button onClick={addBackgroundWidget} className="rounded-full">
                          {t('search.enable', 'Enable')}
                        </Button>
                      )
                    : (
                        <Button variant="destructive" onClick={removeWidget} className="rounded-full">
                          {t('search.disable', 'Disable')}
                        </Button>
                      )}
                  {isWidgetHosted && isDev && (
                    <Button variant="outline" onClick={openDevTools} className="rounded-full border-yellow-500 text-yellow-600 hover:text-yellow-700 hover:bg-yellow-50">
                      DevTools
                    </Button>
                  )}
                </>
              )
            : (
                <>
                  {widget.isSupportNormal() && (
                    <Button onClick={onClickAddNormal} className="rounded-full">
                      {t('search.desktop', 'Desktop')}
                    </Button>
                  )}
                  {widget.isSupportOverlap() && (
                    <Button onClick={() => addWidget(DeployMode.OVERLAP)} className="rounded-full">
                      {t('search.overlap', 'Overlap')}
                    </Button>
                  )}
                  {widget.isSupportTray() && (
                    <Button onClick={() => addWidget(DeployMode.TRAY)} className="rounded-full">
                      {t('search.tray', 'Tray')}
                    </Button>
                  )}
                </>
              )}
        </div>

        {upgradable && (
          <Button
            variant="secondary"
            className="rounded-full bg-yellow-500 hover:bg-yellow-600 text-white"
            onClick={upgradePackage}
            disabled={upgrading}
          >
            {upgrading ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <ArrowUpCircle className="mr-2 h-4 w-4" />}
            {t('search.upgrade', 'Upgrade')}
          </Button>
        )}
      </div>
    </Card>
  )
}
