// src/views/add/WidgetContainer.vue
<script lang="ts" setup>
import { WidgetApi } from '@widget-js/core'
import { WebWidget } from '@widget-js/web-api'
import { nextTick, onMounted, ref } from 'vue'
import { FileFailed, PictureOne } from '@icon-park/vue-next'
import { computedAsync } from '@vueuse/core'

const props = defineProps({
  widget: {
    type: WebWidget,
    required: true,
  },
})

const cellSize = 72
const containerHeight = cellSize * 2
const showPreview = ref(false)

const previewImage = computedAsync(async () => {
  if (props.widget.package && props.widget.package.remote) {
    return `https://${props.widget.package.remote.hostname}${props.widget.package.remote.base}${props.widget.previewImage}`
  }
  else {
    const url = await WidgetApi.getWidgetPackageUrl(props.widget.packageName!)
    return url + props.widget.previewImage!
  }
}, null)

onMounted(async () => {
  await nextTick()
})
</script>

<template>
  <div
    :style="{
      height: `${containerHeight}px`
    }"
    class="widget-container"
  >
    <el-image-viewer
      v-if="showPreview"
      :url-list="[previewImage]"
      show-progress
      @close="showPreview = false"
    />
    <el-image
      v-if="!!widget.previewImage"
      class="preview-image cursor-pointer"
      :src="previewImage"
      alt=""
      fit="contain"
      @click="showPreview = true"
    >
      <template #error>
        <FileFailed />
      </template>
      <template #placeholder>
        <PictureOne />
      </template>
    </el-image>
  </div>
</template>

<style scoped lang="scss">
.widget-container {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
}

.title {
  display: flex;
  height: 36px;
  align-items: center;
}

.preview-image {
  filter: drop-shadow(0px 0px 8px rgba(0, 0, 0, 0.2));
  width: 100%;
  height: auto;
  max-height: 128px;
}
</style>

// src/pages/add/components/widget-container.tsx
import type { WebWidget } from '@widget-js/web-api'
import { WidgetApi } from '@widget-js/core'
import { Image as ImageIcon, ImageOff } from 'lucide-react'
import { useEffect, useState } from 'react'
import { cn } from '@/lib/utils'
import { ZoomImage } from './zoom-image'

interface WidgetContainerProps {
  widget: WebWidget
  className?: string
}

export default function WidgetContainer({ widget, className }: WidgetContainerProps) {
  const [previewImage, setPreviewImage] = useState<string | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState(false)

  const cellSize = 72
  const containerHeight = cellSize * 2

  useEffect(() => {
    const loadPreview = async () => {
      if (!widget.previewImage) {
        setLoading(false)
        return
      }

      try {
        setLoading(true)
        setError(false)

        if (widget.package && widget.package.remote) {
          const remote = widget.package.remote
          const url = `https://${remote.hostname}${remote.base}${widget.previewImage}`
          setPreviewImage(url)
        }
        else if (widget.packageName) {
          const url = await WidgetApi.getWidgetPackageUrl(widget.packageName)
          setPreviewImage(url + widget.previewImage)
        }
      }
      catch (e) {
        console.error('Failed to load preview image', e)
        setError(true)
      }
      finally {
        setLoading(false)
      }
    }

    loadPreview()
  }, [widget])

  return (
    <div
      className={cn('flex flex-col items-center justify-center', className)}
      style={{ height: `${containerHeight}px` }}
    >
      {previewImage
        ? (
            <ZoomImage
              src={previewImage}
              alt="Widget Preview"
              className="w-full h-auto max-h-[128px] object-contain drop-shadow-md cursor-pointer hover:opacity-90 transition-opacity"
              onError={() => setError(true)}
              style={{ display: error ? 'none' : 'block' }}
            />
          )
        : null}

      {/* Fallback states */}
      {(error || (!previewImage && !loading)) && (
        <div className="flex flex-col items-center justify-center text-muted-foreground">
          <ImageOff size="32" className="mb-2" />
          <span className="text-xs">Preview unavailable</span>
        </div>
      )}

      {loading && (
        <div className="flex flex-col items-center justify-center text-muted-foreground animate-pulse">
          <ImageIcon size="32" className="mb-2" />
          <span className="text-xs">Loading...</span>
        </div>
      )}
    </div>
  )
}
